### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by dumblob** [brakulla/brutils#3]
It seems all `br_threaded_object` in readme shall actually say `br_object`, right?

**Comment by brakulla** [comment]
Not really. 

You are right about README being incomplete, but it explains `br_threaded_object`. `br_object` is basically the same thing without creating a thread, therefore if a queued connection is required, it needs another `br_threaded_object` to be its parent. A `br_object` without a parent can only provide direct connection.

I will extend the README to include both (and more) as soon as I can.

**Comment by dumblob** [comment]
Oh, sorry for the fuss - an oversight on my side. Btw. great pack of utilities!

Closing for no action items here.
